name: Steam Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download Mac Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: NecroMatcher-Mac
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: 12575126691

      - name: Display Artifact Contents
        run: ls -R NecroMatcher-Mac
  
